### ISSUE TITLE
Set up CI/CD Pipeline using GitHub Actions - Frontend

### ISSUE THREAD

**Issue by mwinel** [Peer-Desk/peerdesk-webapp#3]
### Description
Set up a CI/CD pipeline using GitHub Actions for a Node.js app with a Docker image. This pipeline will automate the build, test, and deployment of the backend server in a containerized environment, making it easier to manage and maintain.

### Tasks
- Set up a Docker Hub repository to store the backend docker image.
- Configure GitHub Actions to build the Docker image, run unit tests, and push the image to Docker Hub on each commit to the development and main branch.
- Set up a Digital Ocean server to deploy the Docker image and configure GitHub Actions to deploy the Docker image to the server after each successful build and test.
- Ensure that the application is properly secured and follows best practices for performance, security, and accessibility.

### Deliverables
- [ ] A fully functional CI/CD pipeline set up using GitHub Actions for the backend.
- [ ] A documented process for testing and deploying the application to a Digital Ocean server.
- [ ] A set of unit tests that ensures the functionality of the application.
- [ ] A properly configured environment that follows best practices for performance, security, and accessibility.

**Comment by Mohit-Aasirwal** [comment]
I think this issue can be successfully closed as we've implemented vercel instead of doing manual pipelining.
